### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by DHowett** [DHowett/ghostbin#51]

**Comment by DHowett** [comment]
```yaml
database: sqlite:file:///whatever
bindAddress: "0.0.0.0:1024"
proxy: true
ghosts: "...?"
```

**Comment by DHowett** [comment]
```yaml
maximums:
    pasteLength: 1048576
    pasteExpiration: 15d
```

**Comment by DHowett** [comment]
perhaps this:

```yaml
database:
    dialect: sqlite3
    connection: ghostbin.db
    # Example Connection with Secrets
    # connection: "postgresql://user:{{-env POSTGRES_PASSWORD-}}@db.example.net/ghostbin?sslmode=disable"
web:
    - bind: 0.0.0.0:80
    - bind: 0.0.0.0:443
      ssl:
          ca: ca.pem
          cert: cert.pem
          key: key.key
    - bind: 0.0.0.0:8080
      proxied: true
logging:
    components:
        db: true
        web: true
        auth: true
    destination:
        type: file
        path: ./ghostbin.log
application:
    # force_insecure_encryption controls whether passwords will be accepted over HTTP.
    force_insecure_encryption: true
    limits:
        paste_size: 1048576
        paste_cache: 1000
        paste_max_expiration: 15d
```

with the ability to load multiple stacking config files, this could become properly powerful.
